### ISSUE TITLE
[Improvement] Forward STDIN across network

### ISSUE THREAD

**Issue by pkopriv2** [cott-io/iron-releases#10]
To get fully distributed pipelines, we need to support forwarding stdin across the network.   This could eventually lead to greatly enhanced security because secrets will no longer have to be accessible by anchors, e.g.:

```
cp secrets.json - | cut #/db_user #/db_pass | fg @anchor env @/usr/bin/myapp 
```

AC:
* Stdin can be passed to any command.  (ie the above runs)

**Comment by pkopriv2** [comment]
Beginning work.

**Comment by benhammes** [comment]
This will be part of #18
