### ISSUE TITLE
Demonstrate password rotations using docker stacks/containers

### ISSUE THREAD

**Issue by pkopriv2** [cott-io/iron-releases#11]
As a user, I'd like to be able to regularly rotate passwords, so that I can focus on other issues. 

AC: 
* Be able to securely change a password in an existing docker stack file.
* Be able to securely deliver the new stack file to a swarm
* Be able to securely change a password in a generic data file
* Be able to deliver the passwords via environment variables

Notes: 
* This may include demonstrating password changes in remote systems (ie databases) so we can show the complete workflow.

**Comment by benhammes** [comment]
Done, but still needs documentation.

**Comment by benhammes** [comment]
Preston will send Mike a follow up email today. 8/7

**Comment by pkopriv2** [comment]
![image](https://user-images.githubusercontent.com/1661445/43965489-ffcc71b6-9c84-11e8-8465-8ad252e41d40.png)
