### ISSUE TITLE
Dropping nonexistent anchor tag doesn't raise an error

### ISSUE THREAD

**Issue by thedatabuddy** [cott-io/iron-releases#14]
While in an anchor, dropping a tag that doesn't exist in its list of tags doesn't throw an error. A simple <empty stream> is returned as output.

![dropnonexistingtag](https://user-images.githubusercontent.com/31552848/43228747-076d4706-9028-11e8-8d93-9446399ea7bc.PNG)

**Comment by pkopriv2** [comment]
Yup, this breaks the principle of least surprise.  We've got a couple options: 

1. Return an error
2. Print a better message

@ManoharBoorlu What do you think?

**Comment by manoharboorlu** [comment]
I think printing a better message in different color would be much more understanding to the User compared to returning an error.

**Comment by thedatabuddy** [comment]
The same happens while adding a tag that already exists. I guess it would be good if an alert is raised instead of an error, just like Manohar said.

**Comment by benhammes** [comment]
Follow up with Josiah.

**Comment by josiahconely** [comment]
I have that fixed I need to commit

**Comment by benhammes** [comment]
Merged into issue 12
