### ISSUE TITLE
Improvement Document Native Windows Building

### ISSUE THREAD

**Issue by bballfan222** [cott-io/iron-releases#15]
As a user, I'd like the ability to use all of Iron's tools in a native windows environment, so that I can manage machines across any environment and operating system.

As a developer, I'd the like the ability to develop natively in Windows, so that I can better provide support for windows users.

AC:
The user will be able to follow all  instructions and will be able to have a fully functional build.

**Comment by benhammes** [comment]
This is being reviewed here https://github.com/cott-io/iron-core/pull/19

**Comment by benhammes** [comment]
This issue has been merged and is done. AC has been met.
