### ISSUE TITLE
Few hyperlink errors in Developer Documentation site

### ISSUE THREAD

**Issue by manoharboorlu** [cott-io/iron-releases#16]
Few hyperlinks to other parts of the documentation do not work.

![image](https://user-images.githubusercontent.com/25132951/43538991-3254b5d8-9589-11e8-9a8f-c356226f854a.png)

The Prerequisites links to 'Tether Overview' and 'Tether Getting Started' have to be corrected in every page of Commands - <.........> under Tether.

**Errors:**
Tether Overview - _Page not found_
Tether Getting Started - _Takes us to docs/cli/start page_

**Correction:**
Tether Overview - _https://dev.cott.io/docs/tether/overview/_
Tether Getting Started - _https://dev.cott.io/docs/tether/start/_

**AC:**
Clicking the 'Tether Overview' should take us to "Iron (Fe) - Tether Overview" page.
Clicking the 'Tether Getting Started' should take us to "Iron (Fe) - Getting Started" page.

**Comment by benhammes** [comment]
Preston will fix today 8/7
