### ISSUE TITLE
[Bug] Cannot restore empty files in locker 

### ISSUE THREAD

**Issue by benhammes** [cott-io/iron-releases#2]
Steps to recreate: 

1. cp a new file into locker
2. attempt to cp a version with #/size 0

Ex. attempt to restore version 3 in the below screenshot results in an error. 

![screen shot 2018-06-25 at 1 34 02 pm](https://user-images.githubusercontent.com/34721344/41868912-02795b12-787d-11e8-8d36-cf93878f1ac1.png)

Platform and version: Mac, darwin_amd64:0.1.0-beta-28

**Comment by pkopriv2** [comment]
@benhammes I'm gonna be jerk and refer you to https://github.com/cott-io/iron-releases#submitting-bugs.  Please make sure to follow the directions on submitting bugs.  It makes our lives so much easier.

**Comment by pkopriv2** [comment]
Steps to reproduce:

* Upload a new file into locker.
* Try to copy the 0th version of the locker file to the latest.  (e.g. fe locker cp test@cott.com:testing:0 tesst@cott.com:testing)

**Comment by pkopriv2** [comment]
I've assigned myself to this.

**Comment by pkopriv2** [comment]
Remodeled and simplified the storage and lifecycle of locker files.   We now offer full support for viewing and managing deleted files.  Deleted files can be restored and can be written over and history may be viewed on a per name basis.

**Comment by pkopriv2** [comment]
![screen shot 2018-07-05 at 8 58 25 pm](https://user-images.githubusercontent.com/1661445/42422851-38e7b040-82b4-11e8-8336-6179abc386f2.png)

**Comment by pkopriv2** [comment]
There's much more testing evidence to show, but for now the issue has been fixed.
