### ISSUE TITLE
Better REST API input validation

### ISSUE THREAD

**Issue by pkopriv2** [cott-io/iron-releases#21]
Much of our system requires constraints to work properly. currently, these constraints have had little support at any layer - save for maybe the storage layer.

We need to add input validation to each of our api methods to ensure that our system can never obtain an invalid state.

For example, at the user level, domain names take the form "example-io" (letters, numbers, dashes, etc...) - however, this is not enforced anywhere!

AC:
* Accounts APIs Constraints documented and added.
* Identities
* Teams
* Lockers

Corresponding tests added to the /sdk package.

**Comment by benhammes** [comment]
Starting on it today.

**Comment by benhammes** [comment]
Sent to Trello.
